//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymbolicAlgebra.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymbolicAlgebra.Console.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Algebra Console {0}
        ///Copyright 2012-{1} at Lost Particles.
        ///All Rights Reserved for Ahmed.Sadek@LostParticles.net the Author of the library..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix Operators:
        ///&apos;.&apos;  Integration Operator       -- STILL EXPERIMENTAL -- 
        ///&apos;|&apos;  Differentiation Operator
        ///&apos;^&apos;  Power Operator
        ///&apos;*&apos;  Multiplication
        ///&apos;/&apos;  Division
        ///&apos;+&apos;  Addition
        ///&apos;-&apos;  Subtraction
        ///
        ///Prefix Operators:
        ///&apos;%&apos;  Constants Prefix 
        ///
        ///SA&gt; x+x           will produce 2*x
        ///SA&gt; (x^2+2*x)|x   will produce  2*x+x
        ///SA&gt; (2*x).x       will produce  x^2
        ///
        ///SA&gt; :Q            to Quit  like VIM ;)
        ///
        ///Custom Function Declaration:
        ///&apos;:=&apos; f(x) := x^3.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the library in your C# program directly:
        ///
        ///Using SymbolicAlgebra;
        ///
        /// // Assign variable immediately
        ///var x = new SymbolicVariable(&quot;&quot;x&quot;&quot;);
        ///var y = new SymbolicVariable(&quot;&quot;y&quot;&quot;);
        ///
        /// // or parse the expression directly.
        ///var myeq = SymbolicVariable.Parse(&quot;&quot;(a+b)^2&quot;&quot;);
        ///
        /// // then use the language overloaded arithmatic opertors directly.
        ///var total = (x*y*x).Differentiate(&quot;&quot;x&quot;&quot;);
        ///
        ///Finally  .. Enjoy.
        /// </summary>
        internal static string Help2 {
            get {
                return ResourceManager.GetString("Help2", resourceCulture);
            }
        }
    }
}
